#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intakeMotor,   tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "convayor_bot.c"
#include "joystickDriver.c"






task main()
{
	init();
	forward(12, 100);
	turnLeft(45, 50);
	forward(24, 100);
	turnLeft(90, 50);

	fowardUntilLine(20, 50);
	motor[intakeMotor] = 20;
	forward(5, 10);
	motor[intakeMotor] = 0;
	backward(24, 50);
	moveArm(35, 50);
	turnLeft(90, 50);
	fowardUntilLine(20, 100);
	turnLeft(80, 100);
	lineFollow(38, 20, true, 50);
  turnRight(90, 100);
  moveArm(10, 50);
  forwardTime(2, 50);
  dispense_all();
	//backwardTime(3, 100);

	//fowardUntilLine(20, 100);
	//turnRight(40, 100);
	//forward(30, 60);
	//moveArm(10, 50);
	//turnRight(90, 50);
	//forward(6, 50);
	//dispense_all();

	//propagate_wavefront(robot_x, robot_y);
	//print_map();
	// your code goes here
	while(true){}
}
