#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     armMotor,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     intakeMotor,   tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "drive_train.c"
#include "joystickDriver.c"
#include "wave_front.c"

const float DegreesPerUnit = UPR/360;

void move_arm(int degrees, int speed){
	int target = (degrees*degreesPerUnit)*2; //multiplying by two for gear ratio
	nMotorEncoder[armMotor] = 0;

	if(degrees > 0){
		motor[armMotor] = speed;
		while(nMotorEncoder[armMotor] < target){}
	}else{
		motor[armMotor] = -speed;
		while(nMotorEncoder[armMotor] > target){}
	}
	motor[armMotor] = 0; //target reached
	wait10Msec(10);
}

void dispense_all(){
	motor[intakeMotor] = -100;
	wait10Msec(150);
	motor[intakeMotor] = 0;
}


task main()
{
	forward(20, 100);
	foward_until_line(20, 50);
	turnRight(40, 50);
	forward(18, 60);
	move_arm(50, 50);
	turnRight(90, 50);
	forward(4, 50);

	//propagate_wavefront(robot_x, robot_y);
	//print_map();
	// your code goes here
	while(true){}
}
